### PR TITLE
Fix/flow issues

### PR DESCRIPTION
**Pull request by kacgrzes**
Hello @arekkas sorry for bothering you, but #405 was missing flow typing and builds were [failing](https://travis-ci.org/ory/editor/builds/239873238). I fixed that with this commit. My bad!

### CODE REVIEW

**Comment by arekkas** [comment]
Oh damn, apparently the CI isn't running on forks, that is fixed now. Could you refresh this commit here? By the way, I also overlooked that you didn't sign your commit which is required for our DOC (see [here](https://github.com/ory/editor/blob/master/CONTRIBUTING.md#developers-certificate-of-origin)). If you do `git commit --amend -s` and then force push, it should build this PR and also comply with our contribution guidelines :)

**Comment by arekkas** [comment]
Thank you! CI runs now, let's see if it becomes green :D

**Comment by kacgrzes** [comment]
@arekkas one more thing sir, could you merge this fix into 0.2.11 and rebuild new version?

**Comment by arekkas** [comment]
it's being built as 0.2.12 right now :) should be done in ~10mins

**Pull request merged**
