### PR TITLE
Plugin controls renderers

### PR DESCRIPTION
**Pull request by PeterKottas**
Dummy PR (for now) so that you can check out the code changes discussed in #580

### CODE REVIEW

**Comment by aeneasr** [comment]
Hey; I'll give this a review later. 0.4.0 is already merged in master, so please rebase on master :)

**Comment by aeneasr** [comment]
Oh man, what a mess. Issue is, I'm out of office the next two weeks and will probably not be able to give this a lot of attention. I'll try to see if I can do this tonight though. Is the whole PR missing?

**Comment by aeneasr** [comment]
Actually this is merged. Are you sure you're not mistaken? I checked out 0.4.0, pulled the changes, created a diff patch, applied it to a branch off master and there were only a few code formatting issues. On that node, please disable your autoformat from VSCode, it seriously messes with the PRs and makes them incredibly hard to merge. Please use `npm run format` only, and run it before every commit.

There was one change which isn't on master at the moment, see screen:

image

Left side is current master, right side is after applying the patch from 0.4.0. I'm not sure which one is the right one here, do you?

**Comment by aeneasr** [comment]
This PR is also messed up because it's based off 0.4.0, please do:

```
git remote add peter https://github.com/PeterKottas/editor.git
git remote add ory https://github.com/ory/editor.git
git fetch ory
git fetch peter
git checkout peter:plugin-controls-renderers -b plugin-controls-renderers-patch
git patch ory/master > ~/diff-040.patch
git checkout ory/master -b plugin-controls-renderers-new
git apply ~/diff-0.4.0.patch
yarn run format
# Optionally update lockfiles if needed:
# yarn
git push peter HEAD:plugin-controls-renderers-new
```

Then create a new PR from `peter/plugin-controls-renderers-new` to `ory/master`.

**Comment by PeterKottas** [comment]
Ok, this is strange.
First off, I think the formatting will be resolved now, I see you added a precommit hook to run prettier, so it will just fix whatever I do. (Don't want to mess with vs code settings as then it affects my other projects. I think maybe I could do a project only setting, but with the prettier commit hook, all should work just fine from now on)

Secondly, yeah I branched this off from 0.4.0 initially. I'll try what you suggested.

But most importantly, if you go to https://github.com/ory/editor/blob/master/packages/plugins/content/slate/src/index.js#L51 see the plugins are just copied. But in order for the changes from that PR to be there, it should look something like this :   https://github.com/ory/editor/blob/0.4.0/packages/plugins/content/slate/src/index.js#L53
See the difference, the plugins here are constructed by also adding the inner plugins that are initialized in the plugin objects themselves. There's of course many more changes but this can serve as an example. As a result, if you now go to the live demo, you'll see the lists are not working properly. 

Now maybe git tells you it's "merged" but it's definitely not merged properly (unless of course I am missing something)  

PS: Looking at this mess now, I think I'll just delete this branch, start new one from master (after this is resolved) and just copy the stuff manually. It will be much simpler. I basically changed just the image plugin, so I'll copy the whole thing over to a new branch and all should work just fine then.

**Comment by PeterKottas** [comment]
By the way, that diff actually looks good. But if I go to branch (even here in github UI) it's just not there.

**Comment by PeterKottas** [comment]
In fact, (IMHO) if you just take the right side of https://github.com/ory/editor/pull/570/files#diff-526c2546141374aa41580dbbeac4f826 and the diff you posted before, it might all work just fine. (That PR was basically just fixing the lists)

**Comment by aeneasr** [comment]
> 

PS: Looking at this now, I think I'll just delete this branch, start new one from master (after this is resolved) and just copy the stuff manually. It will be much simpler. I basically changed just the image plugin, so I'll copy the whole thing over to a new branch and all should work just fine then.

Use the commands I gave you to do that. No need for manual work!

I'll check out your analysis a bit later and update master

**Comment by PeterKottas** [comment]
Closed in favor of #587, I think we continue talking about the list changes here though. Hopefully it will be resolved today anyways.

**Pull request closed without merging**
