### PR TITLE
Feature/upgrade material ui 1.2.0 vol. 3

### PR DESCRIPTION
**Pull request by PeterKottas**
All the changes in #535 done by @warp are included. There's one extra commit that fixes the 2 remaining issues. Namely the preview button wasn't clickable behind bottom toolbar and floating toolbar appeared on wrong place in slate. All fixed as far as I can say.

Also I had to start:watch for development which is undocumented. The build was weirdly unstable (on windows here) and failed multiple times I used the documented development commands from read-me.

Note that new default for buttons in MUI is light gray which imho is fine. If you want to revert to previous blueish color, that can of course be done.

Last note, after committing my changes, the docs got regenerated but there was whole bunch of weird changed (multiple extra links pointing to my fork repo, links changed from hash to permanent and so on) so I didn't commit those. Not sure what that was about.

### CODE REVIEW

**Comment by PeterKottas** [comment]
Ok what the hell is this, bot complains about signed-off but 
git show HEAD --show-signature shows it's signed locally and even here https://github.com/ory/editor/pull/547/commits/7b11e426496478f635ae8edffcd4642f1780a1d3 you can see it's signed off. I don't know man ...

**Comment by arekkas** [comment]
Don't worry about the sign off :) Thank you for the changes, I'll check them out later today or latest tomorrow. There's however one conflict remaining, namely `packages/renderer/src/index.test.js` - could you resolve that?

**Comment by PeterKottas** [comment]
Ok error, conflict and some warnings are fixed. Sign-off still kicking my ass, thanks for not being picky about that.

**Comment by arekkas** [comment]
Thank you! The only thing left to be fixed is the bottom toolbar when having a TextField or something simlar ascolors are black on black:

image

image

Apart from that this seems good to go!

**Comment by PeterKottas** [comment]
Bottom toolbar fixed, I've however found one more problem. When you "move things" and drop something in the trash, it doesn't work. I suspected some problems as there was a console warning. I'll be looking into this tomorrow.

**Comment by PeterKottas** [comment]
Turns out it was pretty straight forward. All done from me then. Back to you @arekkas ;)

**Comment by arekkas** [comment]
The video component still has the black color bug, everything else looks awesome!

**Comment by arekkas** [comment]
Oh and the parallax background component

**Comment by arekkas** [comment]
And the HTML5 video is no longer clickable in edit mode. It is however possible that this is a firefox regression issue, will confirm

**Comment by arekkas** [comment]
Yes the HTML5 video seems to be an issue with firefox only, opened an issue for tracking this: #548

**Comment by PeterKottas** [comment]
Ok, will check it out.

**Comment by PeterKottas** [comment]
Ok, those 2 done.

**Comment by arekkas** [comment]
Awesome! :)

**Comment by PeterKottas** [comment]
Cheers, how does the release cycle work with ory? Will you be pushing this to npm right away? Seen the pre-release and wanted to play around with it but couldn't pull it down in my project. I tried pulling from git directly (like I did many times before) but with this repo it didn't work. Not sure why ... my project.json

```
...
"ory-editor": "git+https://github.com/ory/editor#af93e462d6057b878bc9495764a9b4e0a51e7856",
"ory-editor-plugins-slate": "git+https://github.com/ory/editor#af93e462d6057b878bc9495764a9b4e0a51e7856",
...
```

**Comment by arekkas** [comment]
Unless CI fails, this should be commited to: https://www.npmjs.com/package/ory-editor-core

**Comment by arekkas** [comment]
Well, CI fails because of an invalid token. I think all NPM tokens were revoked due to security issues with npm. I'll check it tomorrow

**Comment by PeterKottas** [comment]
Yeah that's right, ok no rush, tomorrow is fine for me.

**Comment by arekkas** [comment]
Ok, release worked now - available as 0.3.0

**Pull request merged**
