### PR TITLE
vendor: update lerna, remove parallel flag from build

### LINKED ISSUE #422: Cannot build and run the examples. “npm run build” fails
Attempted to perform a fresh install per the readme instructions.  I am unable to get a successul build.

Here is the console output from `git clone` and `npm i`:
https://gist.github.com/paulkoanui/e50b7f9289a8a8b658050a803e493f9a 

Next, here is the console output from `npm run build`.  This step fails.
https://gist.github.com/paulkoanui/357e8b08e8b76ea384339e4141d43345 

It fails to compile the examples.  Any idea why a vanilla install like this wouldn’t work?

Thanks,
Paul

### PR DESCRIPTION
**Pull request by inyono**
Closes #422

### CODE REVIEW

**Comment by arekkas** [comment]
LGTM

**Comment by arekkas** [comment]
@inyono for some reason CI with `npm i` fails, can you take a look?

**Comment by inyono** [comment]
Seems like travis runs out of memory (https://github.com/travis-ci/travis-ci/issues/4192#issuecomment-118631896). Not sure what to do about that :/

**Comment by arekkas** [comment]
Ok, I'll check it when I'm back, maybe switching to yarn or clearing caches can help.

**Comment by arekkas** [comment]
fixed in #430

**Pull request closed without merging**
