### PR TITLE
Slate link

### PR DESCRIPTION
**Pull request by PeterKottas**
Fix for #549

### CODE REVIEW

**Comment by arekkas** [comment]
please `git commit --amend -s && git push origin --force` :)

**Comment by PeterKottas** [comment]
That's what I tired before but still didn't fix that sign-off nonsense. Will try again.

**Comment by PeterKottas** [comment]
Finally ...

**Comment by arekkas** [comment]
Thanks!

**Comment by PeterKottas** [comment]
Np

**Pull request merged**
