### PR TITLE
npm: explicitly set packages as public for public npm organization pu…

### PR DESCRIPTION
**Pull request by colepacak**
…blishing

Signed-off-by: colepacak <cole@favish.com>

### CODE REVIEW

**Comment by colepacak** [comment]
We're embracing this project as an inclusion into a Drupal module. For the short term, we've forked the repo, but we'd like to upstream any improvements that would be helpful in a general way for you guys. These changes enable us to group packages publicly under an NPM organization, which is the default for regular NPM accounts.

**Comment by aeneasr** [comment]
Can you please point to the documentation where this setting is specified? I can not find it in the official npm docs.

**Comment by colepacak** [comment]
We had to piece this one together, so bear with me.

Packages can be scoped to an organization (e.g. material-ui).
_https://www.npmjs.com/docs/orgs/publishing-an-org-scoped-package.html_

"When publishing scoped packages, the access level defaults to restricted. If you want your scoped package to be publicly viewable (and installable) set --access=public"
_https://docs.npmjs.com/misc/config#access_
_https://www.npmjs.com/docs/orgs/publishing-an-org-scoped-package.html_

publishConfig sets "config values that will be used at publish-time. It's especially handy if you want to set ... access".
_https://docs.npmjs.com/files/package.json#publishconfig_

**Comment by aeneasr** [comment]
Thank you for the clarification!

**Pull request merged**
